name: CI
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - ".vscode/**"
      - ".devcontainer/**"
      - ".gitignore"
      - "**.md"
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    container:
      image: python:3.12-bullseye

    steps:
      - uses: Kesin11/actions-timeline@v2

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Package
        run: |
          uv sync --dev

      - name: Lint
        run: uv run ruff check --output-format=github

      - name: Format
        run: uv run ruff format --check

      - name: Test
        run: uv run pytest
